name: CI

on:
  push:
  pull_request:
  schedule:
    # Weekly Tuesday 6AM build
    # * is a special character in YAML so you have to quote this string
    - cron: '0 6 * * 2'

env:
  PYSYN_CDBS: "https://ssb.stsci.edu/trds"

jobs:

  dev_deps_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch tags
      run: git fetch --prune --unshallow --tags
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install and build
      run: |
        sudo apt-get install libxml2-utils
        python -m pip install --upgrade pip setuptools
        python -m pip install astropy==4.1rc2
        python -m pip install git+https://github.com/spacetelescope/synphot_refactor.git@master#egg=synphot
        python -m pip install -e .[test]
    - name: Test with dev deps
      run: pytest --open-files --remote-data

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch tags
      run: git fetch --prune --unshallow --tags
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install and build
      run: |
        python -m pip install --upgrade pip setuptools scipy
        python -m pip install astropy==4.1rc2
        python -m pip install -e .[test]
    # NOTE: If TRDS cannot take the hit, disable --remote-data
    - name: Run tests
      run: pytest --open-files --remote-data

  osx:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch tags
      run: git fetch --prune --unshallow --tags
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install and build
      run: |
        python -m pip install --upgrade pip setuptools scipy
        python -m pip install astropy==4.1rc2
        python -m pip install -e .[test]
    - name: Run tests
      run: pytest --open-files
