name: CI

on:
  push:
  pull_request:
  schedule:
    # Weekly Tuesday 6AM build
    # * is a special character in YAML so you have to quote this string
    - cron: '0 6 * * 2'

env:
  PYSYN_CDBS: "https://ssb.stsci.edu/trds"

jobs:
  other_oses:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch tags
      run: git fetch --prune --unshallow --tags
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install and build
      run: |
        python -m pip install --upgrade pip setuptools scipy
        python -m pip install astropy==4.2rc1
        python -m pip install -e .[test,all]
    - name: Run tests
      run: pytest --open-files --remote-data
