name: When Opened

on:
  issues:
    types:
    - opened
  pull_request_target:
    types:
    - opened

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Label PR
      uses: actions/labeler@v4
      if: github.event_name == 'pull_request_target' || github.event_name == 'pull_request'
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: 'Comment Draft PR'
      uses: actions/github-script@v7
      if: github.event.pull_request.draft == true
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 Thank you for your draft pull request! Do you know that you can use `[ci skip]` or `[skip ci]` in your commit messages to skip running continuous integration tests until you are ready?'
          })
    - name: Special comment
      uses: pllim/action-special_pr_comment@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
